# SRB2 Legacy

name: macOS

on:
  push:
    branches: [ "next", "master", "ci" ]
  pull_request:
    branches: [ "next", "master" ]

jobs:
  build:
    continue-on-error: true
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: brew install --formula sdl2 sdl2_mixer game-music-emu miniupnpc libopenmpt cmake

    - name: Configure CMake
      run: |
        cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=Release -DSRB2_CONFIG_HAVE_GME=OFF -DSRB2_CONFIG_HAVE_OPENMPT=OFF

    - name: Build TSoURDt3rd
      run: ninja -C build

    - name: Upload build artifact
      uses: actions/upload-artifact@v4
      with:
        name: srb2tsourdt3rd_macOS_aarch64-${{ github.sha }}
        path: |
          build/bin
